KOKKOS_SETTINGS=KOKKOS_SRC_PATH=/home/akomporday/git-project/include KOKKOS_DEVICES=OpenMP GTEST_PATH=/home/akomporday/git-project/include/tpls/gtest KOKKOS_PATH=/home/akomporday/git-project/include/install/install

all:
	$(MAKE) -f /home/akomporday/git-project/include/example/fixture/Makefile KOKKOS_SRC_PATH=/home/akomporday/git-project/include KOKKOS_DEVICES=OpenMP GTEST_PATH=/home/akomporday/git-project/include/tpls/gtest KOKKOS_PATH=/home/akomporday/git-project/include/install/install

test: all
	$(MAKE) -f /home/akomporday/git-project/include/example/fixture/Makefile KOKKOS_SRC_PATH=/home/akomporday/git-project/include KOKKOS_DEVICES=OpenMP GTEST_PATH=/home/akomporday/git-project/include/tpls/gtest KOKKOS_PATH=/home/akomporday/git-project/include/install/install test

clean:
	$(MAKE) -f /home/akomporday/git-project/include/example/fixture/Makefile KOKKOS_SRC_PATH=/home/akomporday/git-project/include KOKKOS_DEVICES=OpenMP GTEST_PATH=/home/akomporday/git-project/include/tpls/gtest KOKKOS_PATH=/home/akomporday/git-project/include/install/install clean
